DATA SEGMENT
PRINT DB "Hello World!", 0AH, 0DH, '$' ; 定义一个字符串，以 '$' 结束
DATA ENDS

STACK SEGMENT STACK
DW 20 DUP (0) ; 为堆栈段分配空间
STACK ENDS

ASSUME CS:CODE, DS:DATA, SS:STACK

CODE SEGMENT
START:
MOV AX, DATA
MOV DS, AX ; 将段地址DATA送入DS中
MOV DX, OFFSET PRINT ; 将字符串地址送入DX中
MOV AH, 09H
INT 21H ; 调用INT 21H的9号中断
MOV AH, 4CH ; 返回DOS系统
INT 21H
CODE ENDS

END START